services:
  app:
    build:
      context: .
      target: app
    env_file:
      - .env
    ports:
      - "127.0.0.1:${APP_PORT:-4000}:80"
    volumes:
      - ./storage:/var/www/html/storage
    networks:
      - eftkad

networks:
  eftkad:
    driver: bridge
